exports.kittens = [
  {
    "url": "https://www.flickr.com/photos/golf_pictures/3017331832",
    "title": "Fat Cat Moe by Dan Perry, on Flickr",
    "description": "In all his glory",
    "imageUrl": "https://farm4.staticflickr.com/3057/3017331832_29ec5246bb_b.jpg",
    "imageAlt": "Fat cat lays on the carpet, fluffy tummy exposed",
  },
  {
    "url": "https://www.flickr.com/photos/elsie/5062307",
    "title": "Fat cat by Les Chatfield, on Flickr",
    "description": "After me children... The Fat Cat Sat on the Mat",
    "imageUrl": "https://farm1.staticflickr.com/4/5062307_35a71740a2_o_d.jpg",
    "imageAlt": "Cat in a corner tries to groom himself but his tum-tum is just too big",
  },
  {
    "url": "https://www.flickr.com/photos/50826080@N00/15056323332",
    "title": "A Fat Cat by Stephen Bowler, on Flickr",
    "description": "Get chasing those mice tubs",
    "imageUrl": "https://farm4.staticflickr.com/3850/15056323332_e970a3911b_b_d.jpg",
    "imageAlt": "Tubby tuxedo cat trying to enjoy the outdoors in style",
  },
  {
    "url": "https://www.flickr.com/photos/chucknado",
    "title": "Fat by Charles Nadeau, on Flickr",
    "description": "",
    "imageUrl": "https://farm8.staticflickr.com/7159/6513884943_b1665018a8_b_d.jpg",
    "imageAlt": "Majestic Tubbers surveys his kingdom from atop the highest rock",
  },
  {
    "url": "https://www.flickr.com/photos/chikawatanabe",
    "title": "Musubi broke cat door by Chika Watanabe, on Flickr",
    "description": "The white square is the frame of our cat door. She has outgrown the door...hmmmm....",
    "imageUrl": "https://farm1.staticflickr.com/82/241279678_4380865f6d_b_d.jpg",
    "imageAlt": "Musubi, a grey and white tubby kitty, tries to ignore the door frame stuck around her big tum-tum while she eats more food",
  },
  {
    "url": "https://www.flickr.com/photos/dq090702/2837577272",
    "title": "Fat Cat by brokinhrt2, on Flickr",
    "description": "This is Chloe's first big baby boy. He doesn't have a real name like his brother but we do call him fat cat most of the time. All he does is eat and sleep. He loves to lay on his back and he loves to have his belly rubbed & his lower back close to his tail.",
    "imageUrl": "https://farm4.staticflickr.com/3180/2837577272_1ed4ca40b0_b_d.jpg",
    "imageAlt": "Fat Cat heard yoga would help with his back problems, but in the middle of doing child's pose he fell asleep",
  },
  {
    "url": "https://www.flickr.com/photos/allenthepostman",
    "title": "Fat Cat by Allen Watkin, on Flickr",
    "description": "enjoying the rare winter sunshine...Dec 2008",
    "imageUrl": "https://farm4.staticflickr.com/3244/3074511696_c0b62863a0_b_d.jpg",
    "imageAlt": "A beautiful, gray persian with greens eyes looks back in disgust. They are not tubby, they are just floofy.",
  },
  {
    "url": "https://www.flickr.com/photos/44901254@N00/1410005867",
    "title": "This is Billie, she thinks she's Gorgeous! (She really is) by buckle1535, on Flickr",
    "description": "It's true, what they say about females becoming fat after they're \"spade.\"",
    "imageUrl": "https://farm2.staticflickr.com/1124/1410005867_eaac1534a6_b_d.jpg",
    "imageAlt": "Orange and white sweet, baby tubbers displaying white belly fur",
  },
  {
    "url": "https://www.flickr.com/photos/cotaro70s/3107587364",
    "title": "fat cat by cotaro70s, on Flickr",
    "description": "",
    "imageUrl": "https://farm4.staticflickr.com/3221/3107587364_e265429c69_b_d.jpg",
    "imageAlt": "Floofy, calico persian stalks prey",
  },
];
